[project]
name = "custody"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michael Ebert", email = "ebe@gmx.de" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
custody = "custody.cli:main"

[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"
